[workspace]
members = [
    "crates/client",
    "crates/entities",
    "crates/migrations",
    "crates/shared",
    "crates/spyglass",
    "crates/tauri",
    # Publically published crates
    "crates/spyglass-plugin",
    "crates/spyglass-lens",
    "crates/spyglass-rpc",
    # Experimental
    "crates/spyglass-clippy",
]

[profile.release]
codegen-units = 1
lto = true
incremental = false
opt-level = "s"

[profile.sentry]
inherits = "dev"
debug = true

# NOTE: Fixes an issue running ggml in debug mode on windows
[profile.dev.package.ggml-raw]
opt-level = 3

[profile.dev.package.llama-rs]
opt-level = 3